version: '3.4'

services:
    webapi:
        image: ${DOCKER_REGISTRY-}webapi
        container_name: WebApi
        build:
            context: .
            dockerfile: src/CodeNotes.API/Dockerfile
        depends_on:
            - db
    
    db:
        image: postgres:latest
        container_name: Database
        environment:
            - POSTGRES_DB=codenotes
            - POSTGRES_USER=codenotes
            - POSTGRES_PASSWORD=codenotespwd
        volumes:
            - ./.containers/database:/var/lib/postgresql/data
        ports:
            - 5432:5432
            